name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo yum update -y
            sudo yum install git -y
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm install 20
            nvm use 20
            git clone https://<git access token>@github.com/singh12345akshay/devops.git /home/ec2-user/devops
            cd /home/ec2-user/devops/frontend  
            npm install
            npm install sharp
            npm run build
