name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PEM file
        run: |
          echo "${{ secrets.EC2_PEM_FILE }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ec2-key.pem
          port: ${{ secrets.PORT || 22 }}
          script: |
            sudo yum update -y
            sudo yum install git -y
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm install 20
            nvm use 20
            git clone https://<git access token>@github.com/singh12345akshay/devops.git /home/ec2-user/devops
            cd /home/ubuntu/frontend 
            npm install
            npm install sharp
            npm run build

      - name: Clean up PEM file
        run: rm ec2-key.pem
